# MIT License
#
# Copyright (c) 2024 Anja Sheppard, University of Michigan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# SLIMVDB
voxel_size: 0.02
sdf_trunc: 0.1
space_carving: False
prune_interval: 10

# Reconstruction
fill_holes: True
min_weight: 8.0

# RealWorld
apply_pose: True
preprocess: True
min_range: 0.5
max_range: 3.5
rgbd: True
realtime_segmentation: False
render_img_width: 640
render_img_height: 360

# Colors for Labels
color_map:
  0: [0, 0, 0]
  1: [0, 0, 255]
  2: [233, 89, 48]
  3: [0, 218, 0]
  4: [149, 0, 240]
  5: [222, 241, 24]
  6: [255, 206, 206]
  7: [0, 224, 229]
  8: [106, 136, 204]
  9: [117, 29, 41]
  10: [240, 35, 235]
  11: [0, 167, 156]
  12: [249, 139, 0]
  13: [225, 229, 194]